server:
  port: "8080"
  environment: "development"
  readTimeout: 10
  writeTimeout: 10

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "your_password"
  dbname: "dining_app"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "your-secret-key"
  tokenExpiry: 24
  refreshExpiry: 168